CC=g++

make:
	$(CC) -O3 -c ELVA.cc  -o ../obj/ELVA.o
	$(CC) -O3 -c Flag.cc  -o ../obj/Flag.o
	$(CC) -O3 -c Parameter.cc  -o ../obj/Parameter.o
	$(CC) -O3 -c Simulation.cc  -o ../obj/Simulation.o  -std=c++11 
clean:
	$(RM) *.o
